### ISSUE TITLE
[Feature] Apps' Categories

### ISSUE THREAD

**Issue by machiav3lli** [otakuhqz/Omega#1]
As the development is still in its early phases, I'd suggest adding something like auto/manual categories directly on the main screen. If you'd say that's maybe taking the project to a direction you didn't plan for, maybe make it a two modes launcher (normal/direct). And this could be seen as the USP.

A reference implementation and insperation could be found at [Launchtime](https://github.com/quaap/LaunchTime).

**Comment by otakuhqz** [comment]
Thank you for your comment and it's a great idea.
I already have an idea of how to implement it so, of course I will develop something in the early releases.
