### ISSUE TITLE
Text in default search widget stays dark when switching to dark or AMOLED dark theme

### ISSUE THREAD

**Issue by Elbullazul** [otakuhqz/Omega#105]
## Description

When I set the app theme to dark or AMLOED dark, the text in the searchbar doesn't change color, making it very hard to read what I type.

## Expected Behavior

The text in the searchbar widget should be white or light gray to match the light on dark aesthetic

## Actual Behavior

The text stays dark gray. Here is a screenshot:
![Screenshot_20210814-173302_Omega Launcher](https://user-images.githubusercontent.com/15310985/129460846-2f2493d7-979b-4d2f-ab3f-387d7764e4ad.jpg)

## Steps to Reproduce

Set app theme to dark or AMOLED dark and use the omega search widget

Device and OS
• Samsung Galaxy A50
• Android 11
• Rom: OneUI 3.0
• Launcher version: 0.8.0 (from F-Droid Repo), also found on the 0.8.1 debug release

**Comment by otakuhqz** [comment]
Fixed on v0.8.1

**Comment by pedrom34** [comment]
Hey!

I'm having the same issue, but reverted. Search bar text is white on white:

![screenshot](https://i.imgur.com/ibW8w0S.jpg)

**Comment by machiav3lli** [comment]
@pedrom34 which version you're using?

**Comment by pedrom34** [comment]
Sorry, should have mentioned it. Latest 0.8.1.
