### ISSUE TITLE
Custom app drawer labels lost after restarting Omega

### ISSUE THREAD

**Issue by Mokura** [otakuhqz/Omega#11]
## Description

Custom app labels are discarded after restarting Omega Launcher; any apps with custom labels revert to their built in labels.

## Expected Behavior

Custom apps should keep their custom labels (and be re-sorted accordingly, if AZ or ZA Alphabetical Sort is set for the app drawer

## Actual Behavior

App reverted to its built in label.

## Steps to Reproduce

1. Find app you want to rename.
![Screenshot_20200921-152445181](https://user-images.githubusercontent.com/5167919/93813531-42058600-fc21-11ea-9c3f-34bb5e7618b4.jpg)
(At the bottom in this example, "magireko" in Japanese language katakana)

2. Long press on the icon, choose Customize, fill in your new label.
![Screenshot_20200921-152515058](https://user-images.githubusercontent.com/5167919/93813804-a0326900-fc21-11ea-8e8e-99b3daa1b5f7.jpg)

3. App shows in the drawer with the new label, but not sorted yet.
![Screenshot_20200921-152523335](https://user-images.githubusercontent.com/5167919/93813873-c0622800-fc21-11ea-9b52-1069ec2beb2e.jpg)

4. Restart Omega.  App has reverted to its Japanese "magireko" label.
![Screenshot_20200921-152548457](https://user-images.githubusercontent.com/5167919/93813996-f0a9c680-fc21-11ea-89bc-a17781bd3b22.jpg)

## Device and OS

* Device: Google Pixel 3a "sargo"
* Android version: 10
* Launcher version: 
Package: com.saggitt.omega
Version: v0.4.0 (build 32)
Flavor: aospWithQuickstepOmega (release)
Build date: 2020-09-21T18:00Z
ISource: com.android.packageinstaller
VCS Hash: f54b8f5b425cfd64a8b9851e87f829d775e8fc63
* Rom: Bliss 12.11

**Comment by Mokura** [comment]
If you want to install this specific app for reproducibility, you can follow the instructions herehttps://magireco.fandom.com/wiki/Installation

Android workaround > ADB (recommended) > Automatic

You could also try another app with a CJK label, maybe.

**Comment by otakuhqz** [comment]
Fix
