### ISSUE TITLE
[Feature request] Lock apps with fingerprint or password/shema

### ISSUE THREAD

**Issue by Sitavi** [otakuhqz/Omega#117]
Hi ! First of all, thanks a lot to the devs for this project! 

Because we don't want friends or family to be able to open certain apps on a daily basis, I suggest adding the option to lock an apps with fingerprint or password/shema as on the lineageos trebuchet launcher :)

**Comment by otakuhqz** [comment]
added in commit [f17a351](https://github.com/otakuhqz/Omega/commit/f17a3517f5b6f5b7d03269c2059e6eda3f060c2b)

**Comment by Sitavi** [comment]
Wow! Incredible, thanks a lot :)
