### ISSUE TITLE
No dock shortcuts in recents

### ISSUE THREAD

**Issue by Mokura** [otakuhqz/Omega#13]
## Description

Dock shortcuts do not appear when switching between apps, while using the Quickswitch Magisk module.

https://github.com/skittles9823/QuickSwitch

## Expected Behavior

Dock shortcuts appear with quickstep apps list.

## Actual Behavior

Dock shortcuts do not appear.

## Steps to Reproduce

1. Make sure you have some shortcuts in Omega's dock.
![Screenshot_20200921-212240744](https://user-images.githubusercontent.com/5167919/93844209-6d609300-fc6a-11ea-90a5-94e4997abf6e.jpg)

2. Install the QuickSwitch Magisk module and run the installed app.  Select Omega as the recents provider.  Phone automatically reboots.
3. Open your recent apps and notice there's no icons available.
![Screenshot_20200921-212253899](https://user-images.githubusercontent.com/5167919/93844250-8ec17f00-fc6a-11ea-81a7-7faed56eaefa.jpg)

## Device and OS

* Device: Google Pixel 3a "sargo"
* Android version: 10
* Launcher version: 
Package: com.saggitt.omega
Version: v0.4.0 (build 32)
Flavor: aospWithQuickstepOmega (release)
Build date: 2020-09-21T18:00Z
ISource: com.android.packageinstaller
VCS Hash: f54b8f5b425cfd64a8b9851e87f829d775e8fc63
* Rom: BlissROM 12.11

**Comment by otakuhqz** [comment]
Fixed on v0.8
