### ISSUE TITLE
[Request] List-style App Drawer (like Evie)

### ISSUE THREAD

**Issue by traycerb** [otakuhqz/Omega#136]
I'm switching over from the sadly abandoned Evie, and I was hoping for a list-style app drawer, one app per line.  The Current options are grid only, and a minimum of 3 columns.  Here is an example: [Evie List Drawer](https://www.androidcentral.com/sites/androidcentral.com/files/styles/xlarge/public/article_images/2018/02/evie-launcher-app-drawer.jpg)

I just find it a lot easier to read and use.

**Comment by machiav3lli** [comment]
There's already an option in the developer's options to enable some other app's drawer's layout. Check those out and get back to us.

**Comment by traycerb** [comment]
I gave this a try and though I was very much wishing otherwise, unfortunately it's not a good substitute.  These are my 

1. The scroll bar on the side is very narrow.  I have a very low profile case, yet I almost have to pull it off to grasp the scroll bar
2. Scrolling is not instantaneous.  There seems to be an upper speed to scrolling, so if you scroll from 'A' to 'Z' it takes a few seconds for the scroll to catch up.
3. Lastly, this option is buried in the Developer options and hard to find by discovery.  Here is how to get to it: Home settings, 3 dots , Developer options, Layout Mode -> Paged).  Also, is "paged" the right terminology for this?  This isn't what I think of when I think something is "paged," but <shrug> maybe that's the right term.

These are minor points, but for a feature I use countless times/day, it ultimately makes it unworkable implementation.

Overall, I like the project, and it's one that I would be willing to pay for.

**Comment by machiav3lli** [comment]
@traycerb I think you meant vertical list layout not paged?
On 3: the option is in the developer settings as those were some experiments we had (same as Dash before). You can allow to show developer settings directly in settings page by turning show developer settings on.

Those settings possibly won't be in the new 0.9.0 but maybe in the 0.9.1.
