### ISSUE TITLE
Please make labels on the desktop hideable

### ISSUE THREAD

**Issue by l3u** [otakuhqz/Omega#14]
… just like the option for the dock. To save place on the desktop and make it possible to have a clean, minimalistic look. This would be very nice :-)

**Comment by otakuhqz** [comment]
The hide desktop preferences is already implemented. Commit [1687627](https://github.com/otakuhqz/Omega/commit/16876278d555bc2f65ad5facd8b85ee2ae2026d1#diff-99d2f6dc7dae7e9e81bb49d7016ceaa3)

**Comment by l3u** [comment]
Great! Thanks a lot :-)
