### ISSUE TITLE
[Feature Request] At a Glance

### ISSUE THREAD

**Issue by 5lttrz** [otakuhqz/Omega#146]
At a Glance with four main sources of Battery, Date and Time, Now Playing, and Greetings ("Good Morning!", "Good Night!, "Sweet Dreams", "Dont Stay up too late!", "Good Evening!")

This would be a great addition to the visual feel.
PS: Custom fonts for At a Glance would be great too.

Reference: https://f-droid.org/en/packages/ch.deletescape.lawnchair.plah/

https://postimg.cc/RWHg7xzj/38ed8aa4

**Comment by otakuhqz** [comment]
Added to V0.9
