### ISSUE TITLE
Calendar app shows always "7 May"

### ISSUE THREAD

**Issue by cellulosam** [otakuhqz/Omega#147]
Calendar app shows false date

## Description

Calendar app shows always "7 May" as today date

## Steps to Reproduce

1.
2.
3.
4.

## Device and OS

* Device: Samsung Galaxy S5
* Android version: 11
* Launcher version: 0.8.1
* Rom: /e/ os

## Logcat

```
your log here
```

**Comment by machiav3lli** [comment]
What icon pack are you using and do you know for sure if it does support calendar dynamic date?

**Comment by cellulosam** [comment]
Hi, thank you for replying!
I'm using the integrated "system icons" pack provided by the app.
For further problems/bug can I write directly here? For example the backup in a custom folder other than the "Omega folder" fails.

Il 6 febbraio 2022 03:05:41 CET, machiav3lli ***@***.***> ha scritto:
>What icon pack are you using and do you know for sure if it does
>support calendar dynamic date?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/otakuhqz/Omega/issues/147#issuecomment-1030735419
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- Inviato da /e/ Mail.

**Comment by machiav3lli** [comment]
Then maybe your system icon pack doesn't support dynamic icons.

On the custom folder export thingy, are you trying to export to the root folder of the internal storage? If so, Android forbids it. You have to choose a sub folder for this

**Comment by cellulosam** [comment]
For system icon pack I meant your icon pack, the pack included in your omega launcher. 
The system icon pack included in Bliss (the /e/ os' default launcher) supports dynamic icons, because his calendar app normally shows the correct date.

Regarding the custom folder export, I tried to export to the document fodder, not to the root.

Il 6 febbraio 2022 10:13:18 CET, machiav3lli ***@***.***> ha scritto:
>Then maybe your system icon pack doesn't support dynamic icons.
>
>On the custom folder export thingy, are you trying to export to the
>root folder of the internal storage? If so, Android forbids it. You
>have to choose a sub folder for this
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/otakuhqz/Omega/issues/147#issuecomment-1030782680
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- Inviato da /e/ Mail.

**Comment by machiav3lli** [comment]
@cellulosam we don't have a custom icon pack, we use system's one. Dynamic calendar icons can be implemented two ways, either on launcher side overwriting calendar icons (possibly what bliss launcher do), or using icon packs' custom icons, for that the icon pack have to support this (e.g. Delta icons). We have the second one, as this follows and respects iconpacks choices.

**Comment by machiav3lli** [comment]
For the folder issue it may be that there's duch early on, but I don't recall in which version we fixed it. You can either try 0.8.2 (https://t.me/omegalauncher_group/5950) from the community group, try 0.9.0-alpha (https://t.me/omegalauncher_group/7204) or wait for a new release.

**Comment by otakuhqz** [comment]
Fixed on v 0.9. Note tha this feature works with the Google Calendar only for now. Maybe with can consider adding support for more calendar apps, but for now I close the issue as it is no a priority feature.
