### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by codebreaker332** [otakuhqz/Omega#154]
Build version: 0.8.1 Build date: 1981-01-01 01:01:02 Current date: 2022-02-28 11:00:22 Device: Xiaomi Redmi 7 OS version: Android 10 (SDK 29) Stack trace: java.lang.AbstractMethodError: abstract method "void android.view.IRemoteAnimationRunner.onAnimationStart(android.view.RemoteAnimationTarget[], android.view.IRemoteAnimationFinishedCallback)" at android.view.IRemoteAnimationRunner$Stub.onTransact(Unknown Source:48) at android.os.Binder.execTransactInternal(Unknown Source:75) at android.os.Binder.execTransact(Unknown Source:16)

**Comment by machiav3lli** [comment]
Does it happen e.g. when you freely swipe left/right or maybe on an icon?

**Comment by codebreaker332** [comment]
appears when I go to the home screen when exiting the app, I think I managed to reproduce the error, going to add sync account and on the login screen pressing to go to the start screen
