### ISSUE TITLE
[Feature Request] Add additional swipe functionality

### ISSUE THREAD

**Issue by basings** [otakuhqz/Omega#155]
## Description

Currently you can use cover mode in order to hide the folder icon and have only the first entry shown. It would be great to add further swipe functionality to this. E.g. if a folder consists of two apps, you could swipe up (or left to keep the current folder implementation) in order to launch the second entry of the folder immediately. To broaden this feature request it could be possible to add unique swipe behavior to each icon, i.e. what to do on a directional swipe. 

## Expected Behavior / Example

- folder with 4 apps: Signal, Element, Telegram, Wire
  - button tap: opens Signal
  - swipe up: folder view
  - swipe left: Element
  - swipe down: Telegram
  - swipe right: Wire

**Comment by machiav3lli** [comment]
This goes clearly against the function of the swipes navigating through the tabs or the main gestures all while adding a non-intuitive function. For me out of UX perspective it's clear no.

**Comment by basings** [comment]
Sorry for bothering. Ever since using Omega, I don't have multiple tabs anymore. I did not consider this.
