### ISSUE TITLE
Search bar/appdrawer crashes as you type in a query

### ISSUE THREAD

**Issue by theuser18** [otakuhqz/Omega#156]
## Description
After tapping to expand the search bar, after typing a few letters, the search bar/appdrawer crashes back to the homescreen about 75% of the time.

## Expected Behavior
I should be able to complete my search and press enter to find my app or to open the webbrowser.

## Actual Behavior
The search/appdrawer crashes to homescreen.

## Steps to Reproduce

1. Tap search bar to expand it and the appdrawer.
2. Begin typing.

It does not happen 100% of the time. I am using DDG as the search provider.

## Device and OS

* Device: Pixel 3a
* Android version: 12
* Launcher version: 0.8.1
* Rom: CalyxOS

**Comment by otakuhqz** [comment]
Fixex on v0.9
