### ISSUE TITLE
2 feature requests

### ISSUE THREAD

**Issue by bushrang3r** [otakuhqz/Omega#17]
Thanks for this great, actively developed launcher app. Looking forward to seeing its rise.

Some feature ideas:

1. Option to open an app in gestures
2. Sleep option in gestures, ie. double tap screen to sleep.

**Comment by otakuhqz** [comment]
1. added in commit [6cccbea](https://github.com/otakuhqz/Omega/commit/28053e340fef0c618f8226c0ebc6ed32c194c111)
2. added in commit [442959e](https://github.com/otakuhqz/Omega/commit/442959e92a243ea266dec0e2f1684910f99f514b)

**Comment by bushrang3r** [comment]
Thank you sir! 😁
