### ISSUE TITLE
Search bar not working (v0.5.0)

### ISSUE THREAD

**Issue by bushrang3r** [otakuhqz/Omega#18]
## Edit:
Maybe this feature is still being developed.....

## Description
Search bar only searches apps

## Expected Behavior
Should search internet via selected search engine

## Actual Behavior
Apps are filtered live while typing.
Tapping search (enter key) after typing something pops up the app chooser at the bottom of the screen (for me it asks me to select from playstore, f-droid, or aurora).
See screenshot >

![Screenshot_20201001-075007_1](https://user-images.githubusercontent.com/5970120/94747990-32bdcf80-03bb-11eb-8cf1-0908331f1821.jpg)

Device: LG G6 (h870)
Android version: 10
Launcher version: v.0.5.0
Rom: Havoc OS

**Comment by otakuhqz** [comment]
Fixed in commit [2d97e32](https://github.com/otakuhqz/Omega/commit/2d97e32a5c71107a3e6cca0583dcd13a648bb260)
