### ISSUE TITLE
Physical keyboard opens Google

### ISSUE THREAD

**Issue by iTrooz** [otakuhqz/Omega#20]
My keyboard always opens Google in the applications list (see record). Could it be possible to focus on the search bar ?

Record : https://mega.nz/file/dk8x1QgR#heOE37jyYFrp2pLC7AiyZzx-eYNz04SSah-BrZPSv-I

Also, could it be possible to disable Google when typing in the launcher ? (When I press a key, it automatically opens Google)

**Comment by otakuhqz** [comment]
You can change the search provider in the settings search, or go to the drawer setting and disable global search (to use the regular search instead of)

**Comment by iTrooz** [comment]
Sorry, I already did this before posting the issue
btw, I've changed the search provider to Firefox, and it stills open Google, so I think it's more like a default option from launchers (I also had this on Zim launcher, the only difference is that there was auto focus when opening the application drawer)

For info, this only happens with a physical keyboard connected, because Google only opens when I try to type and I've no focus on anything

I'm NOT an Android developer, but maybe you could try something like this ? https://stackoverflow.com/questions/3496720/how-to-set-focus-on-a-textview-when-an-activity-starts
