### ISSUE TITLE
Odd unnamed app shortcuts show up (most probably due to updates)

### ISSUE THREAD

**Issue by l3u** [otakuhqz/Omega#22]
After having done some updates (this may be related to F-Droid updating), some odd unnamed app shortcuts show up in the app list:

![Screenshot_20201023-131559](https://user-images.githubusercontent.com/6770781/97086643-e0bc4280-1624-11eb-98b0-b11679b6b751.png)

When tapping on them, I'm asked if I want to open them with Google Play or with F-Droid. Google Play says I must have a web browser installed to view the content (I of course actually have one). Opening witth F-Droid only yields "No such app found".

Using the preinstalled Quickstep launcher, these shortcuts don't show up.

* Device: Nokia 4.2
* Android version: 10
* Launcher version: 0.5.0

**Comment by l3u** [comment]
PS: After a reboot, those icons are gone again.

**Comment by otakuhqz** [comment]
Then since the icons disappear after reboot, I will close the issue. If the problem still persists I will consider adding a preference to disable the promise icons.

**Comment by l3u** [comment]
Well, they come back after some updates. Until the next reboot. I have seen them again and again …

**Comment by l3u** [comment]
Damn, that was fast :-D
