### ISSUE TITLE
Issue translating strings

### ISSUE THREAD

**Issue by comradekingu** [otakuhqz/Omega#23]
https://hosted.weblate.org/zen/omegalauncher/omegalauncher/nb_NO/?q=state:empty
These could do with some explaining, either here or on Weblate :)

**Comment by machiav3lli** [comment]
Hotseat icons are the icons that are to be found on the bottom bar (or top of the drawer), providing shortcut to the most used apps. So removing one of them manualy would cause it to be replaced with the next appon the listofmost used.
