### ISSUE TITLE
(Feature Request) QuickSwitch Support

### ISSUE THREAD

**Issue by Raul1198** [otakuhqz/Omega#37]
## Description

Since Omega Launcher is based on Lawnchair ( I think so , may be I'm wrong ) it would be better if Omega too have Android 10's  Recent support 

## Expected Behavior

Swipe up to open menu from recent

## Actual Behavior

 Nothing happens

## Steps to Reproduce

1.
2.
3.
4.

## Device and OS

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

```
your log here
```

**Comment by otakuhqz** [comment]
It's something that I have to work on, but yes, support for recents will be added in a near future.

**Comment by otakuhqz** [comment]
add on v0.8
