### ISSUE TITLE
Categorizing apps in tabs needs a restart

### ISSUE THREAD

**Issue by l3u** [otakuhqz/Omega#39]
As of 0.6.2 (installed via the kindly provded F-Droid package), if I change the categorization of apps to tabs in the drawer, I need to restart Omega so that the changes become visible. After pressing "save", the app is checked, but nothing happens. After a restart, the apps are correctly assigned to the respective tab.

This seems to be a newly introduced bug, with 0.5 (installed manually), this worked at once, without a restart.

* Device: Nokia 4.2
* Android version: 11
* Launcher version: 0.6.2

**Comment by otakuhqz** [comment]
It has been resolved in the current development version 0.6.3.

If you want to test it, you an get the las debug version at github actions

**Comment by l3u** [comment]
Nice to see this has already been fixed! It's not so annoying I couldn't wait for it to hit the normal F-Droid update. Thanks :-)
