### ISSUE TITLE
Suggestions for auto-hiding apps, miscellaneous enhancements

### ISSUE THREAD

**Issue by summersab** [otakuhqz/Omega#42]
I've been using Zim for several months, and I just found that you started Omega. So far, it's the best launcher I've EVER used because of the "categories" feature in the drawer. This is something I have always wanted, but no one has done it well. You nailed it!

I have a some suggestions and enhancements. None of them are "requests" - I don't want to seem like I am making demands. I just have some ideas that I think would make your launcher even better!

When I organize my apps, I prefer to have them only be displayed in one location and be hidden everywhere else. I know some people are different, but it keeps things simple for me. With this in mind, here are some ideas for options you could provide:
- If an app is added to the desktop or the dock, automatically add it to the "Hidden App Shortcuts" list.
- Only allow apps to be in one category.
  - When creating a new category, the "Manage apps" picker would only show apps that are in the main "Apps" tab. Apps that are in other categories would be hidden.
- If an app is in the "Hidden App Shortcuts" list, hide it from the "Manage apps" picker when creating categories.
  - This is more of a bug. Currently, you can add hidden apps to a category. However, hidden apps are hidden globally for the entire drawer, so it doesn't show up in the new drawer category. Any hidden app should be filtered out of the the "Manage apps" picker when creating the category.

I hope those make sense. Feel free to ask for clarification, though. I can manually accomplish all of these functions on my own, but it would be nice to have options in the app settings that would let me automatically hide and filter out apps in the ways I described.

Here are a few other miscellaneous ideas that are all low-priority:
- If the "Drawer search bar" is disabled, there is still an empty space where the search bar used to be. Shifting the drawer up so the space isn't wasted would be better.
- Add an option to have the drawer open to the first category by default (it currently opens to the last viewed category)
- There is something wrong . . . "wrong" with text wrapping on app names. For instance, the ProtonMail label shows up as:
  ProtonM
  ail

  I don't know the best way to solve this. Let users adjust the text size of app names? Automatically decrease font size to fit the space? Let app names extend beyond the boundaries of the app icon? I don't know, but it looks weird.
- Provide an "Add app" option to the menu that appears when long-pressing the home screen. This would pull up an app picker.
- Add a ⋮ menu after the last category label in the drawer.
  - This menu would show "Drawer Settings" and "Launcher Settings"
  - It's a bit of a pain to have to go home, long-press, hit "Home settings," edit the drawer, check to see if it looks right, and if not, go home, long-press . . . This button would solve that problem.
- The "Apps Sort" setting is global for all categories in the drawer.
  - It would be nice to allow each category to be sorted differently.
  - A "manual sort" feature where the user can arrange apps in the order they prefer would be a nice option.

Sorry to write so much, but I hope this helps, and I appreciate your work!

**Comment by otakuhqz** [comment]
Hello, there are a lot of good ideas in the above. Some of them are not easy to acomplish but I will try to add as many as possible.

I will be adding comments to this thread when fixing the bugs or adding this features.

**Comment by summersab** [comment]
Yeah, I recognize that many of those ideas aren't the easiest to accomplish. That's why I wanted to make it clear that these aren't "requests" but rather "suggestions" - hopefully, they at least get you thinking!

**Comment by summersab** [comment]
I have a few more suggestions and found a few bugs. It might be better for me to open separate issues for some of these - let me know if you would like me to do that:

- When the homescreen is locked, it is still possible to add widgets.
  - Suggestion: if the "locked" setting is enabled, grey out the "Widgets" option in the long-press context menu.
  - It might also help to add a separator and a label to the bottom of the context menu that says, "Desktop locked."
- Increasing the "Icon Count" setting in the dock above 5 (default) doesn't seem to work all of the time.
  - I don't have steps to reproduce, but after changing it, nothing happens most of the time. The setting seems to only get applied at random.
  - Instead of having a setting, why not automatically adjust this value based on how many icons the user adds? Example:
    - Currently, if a user has 5 icons but removes one, there will still be an empty space in the dock. The user has to go into settings, adjust the "Icon Count" to 4, and then the icons will be evenly spaced.
    - Instead, you could auto-space and auto-scale the icons in the drawer whenever a new icon is added or removed.
- Apps in the dock randomly get rearranged. I think this _might_ only happen if there are more than 5 items in the dock, but occasionally, the icons change order.
- "Lock Desktop" also locks the drawer.
  - I usually uninstall apps by opening the drawer, long-pressing the icon, and dragging it to "Remove" area at the top of the screen.
  - When the desktop is locked, perhaps you could still allow users to "drag-to-remove" apps from the drawer. However, if they try to drop an app on the desktop, show a message indicating that the desktop is locked.

**Comment by otakuhqz** [comment]
* Fixed when the home screen is locked, adding widgets won't be possible.
* Increasing the icon count is working fine to me, but sometimes it require restarting the app. I will review it to apply it when it is closed.
* dock icons are rearranged when the count changes. It will be fixed.
* When the home screen is locked the drawer is not. you are not able to drag the shortcuts to the install option since it's part of the workspace. I could consider allowing to drag the icons to the uninstall button on the home screen, but meanwhile, you can enable the uninstall option in the drawer bubble preference.

**Comment by summersab** [comment]
Dude, that was quick :) I'm between jobs, but if I wasn't, I'd send some money your way. Maybe in a few months . . .

I'll try to figure out what triggers the icon count issue. Let me know if there's anything else you'd like me to test out.

**Comment by otakuhqz** [comment]
Fixed increase icon count not refreshing the grid c84b7c5
