### ISSUE TITLE
Custom icons not applying

### ISSUE THREAD

**Issue by jonjomckay** [otakuhqz/Omega#43]
## Description
When a custom icon is set on a desktop app, the icon doesn't seem to actually apply. As an example, I have the Pixel Icon Pack installed and enabled, and selecting an icon from it either doesn't change the icon to the one I select, or it changes to another icon from the same app instead. Changing the icon on a web shortcut ends up reverting it to the icon for the browser, instead of the selected icon or the favicon too.

## Expected Behavior
Customising an app icon should apply the selected icon.

## Actual Behavior
Customising an app icon does nothing, or applies a different icon.

## Steps to Reproduce

[![Example screen recording](https://adrotog-yt-embed.herokuapp.com/embed?v=v4-w7K6wuHU)](https://www.youtube.com/watch?v=v4-w7K6wuHU "Example screen recording")

## Device and OS

* Device: Xiaomi Mi Mix 3 5G
* Android version: 11
* Launcher version: 0.7.0
* Rom: LineageOS 18.1

**Comment by otakuhqz** [comment]
For some reason, after Google renamed the class to WorkspaceItemInfo it stopped working. I will be fixed in the next release. 
if you change the icon in the drawer and then drag it to the home screen it will work for now.

**Comment by jonjomckay** [comment]
Thanks for the tip! I can confirm that works for proper apps, although not for web shortcuts, but that's fine 😄

**Comment by otakuhqz** [comment]
Fixed in release 7.1
