### ISSUE TITLE
Adjustable font size on desktop

### ISSUE THREAD

**Issue by mahdi1234** [otakuhqz/Omega#44]
With 0.7.0 it seems to be possible change font size of drawer, but not on desktop, unfortunately this is one of two thing blocking me to use Omega as my primary launcher is it looks really bad imo.

![omega_desktop](https://user-images.githubusercontent.com/1097047/106198255-bb9f1900-61ab-11eb-9013-7b7d31c62503.png)

**Comment by otakuhqz** [comment]
Fixed in commit bf8e169
it will require a manual restart to apply it. It will be auto-applied in the future when a listener is set up.
