### ISSUE TITLE
Less distracting border for group of icons in Amoled mode

### ISSUE THREAD

**Issue by mahdi1234** [otakuhqz/Omega#45]
With Amoled mode it's pretty distracting to have whitish line over group of icons.

This is Omega 0.7.0

![omege_background](https://user-images.githubusercontent.com/1097047/106198567-1f294680-61ac-11eb-9ba5-5a7e783160f5.png)

a this is Lawnchair which I find better imo

![lawnchair](https://user-images.githubusercontent.com/1097047/106198618-2cdecc00-61ac-11eb-9b85-62463d1137c3.png)

please consider this adjustable, it's one of things preventing me to use Omega as primary launcher.

**Comment by mahdi1234** [comment]
Here's the whole screen Lawnchair

![Screenshot_20210207-234943880](https://user-images.githubusercontent.com/1097047/107161816-22d08080-6997-11eb-9022-32d39a7f8b19.jpg)

and 0.7.1 Omega, note it looks relatively ok (at least on mine) laptop, but much more distracting on Amoled screen of phone.

![Screenshot_20210207-234959158](https://user-images.githubusercontent.com/1097047/107161824-2d8b1580-6997-11eb-97c7-7b32910a3b47.jpg)

**Comment by 5lttrz** [comment]
Is this issue fixed?

**Comment by machiav3lli** [comment]
@5lttrz yes
