### ISSUE TITLE
F-Droid main repo inclusion?

### ISSUE THREAD

**Issue by ClockGen** [otakuhqz/Omega#47]
Original lawnchair v2 used many proprietary google libs and included several prebuilt jars, so we couldn't include it in F-Droid. Most notably, framework.jar. Is it possible to provide a separate repo with build scripts, etc to actually build it, so this launcher would be fully buildable from source? It would be greatly appreciated if there also would be a separate flavor without proprietary google libraries.

**Comment by otakuhqz** [comment]
We have been talking about that in the telegram channel, It will make some tests to check what would be affected if I get rid of framework.jar. 
I will try to remove all the prebuilt jars but that might take some days because the app is now in the IzzyOnDroid repo and I'm getting more issues and bugs.

**Comment by Penguinjumper** [comment]
I very much second this. Would be great to have a nicely looking FOSS launcher on f-droid! :)

**Comment by nonaybay** [comment]
<a href="https://github.com/otakuhqz/Omega/issues/60#issue-808108411">https://github.com/otakuhqz/Omega/issues/60#issue-808108411</a>

**Comment by otakuhqz** [comment]
Closed as there is no plan to include it in the main F-droid repo due to some libs needed to compile the app

**Comment by bobberb** [comment]
> Closed as there is no plan to include it in the main F-droid repo due to some libs needed to compile the app

Out of curiosity, what are the libs that izzy doesn't need but fdroid does?
