### ISSUE TITLE
Backup does not save widgets or bookmarks

### ISSUE THREAD

**Issue by summersab** [otakuhqz/Omega#48]
## Description
Restoring a backup to a fresh install of Omega does not restore widgets or bookmarks.

## Expected Behavior
All items on the desktop should be restored after importing a backup.

## Actual Behavior
Widgets and bookmarks are not restored. Folders might be impacted, too - I had a folder, but it only included bookmarks, so that may be why it wasn't restored.

## Steps to Reproduce
For some reason, I couldn't install v0.7.0 in-place over v0.6.3, so I did the following:

1. Backed up the app in "Advanced Settings"
2. Removed the app
3. Installed new version
4. Restored backup

## Device and OS
* Device: LG Nexus 5X (bullhead)
* Android version: 10
* Launcher version: 0.7.0 (build 115)
* Rom: LineageOS 17.1

**Comment by otakuhqz** [comment]
fixed on v0.8
