### ISSUE TITLE
[v0.7.0] Options for double tap gesture don't execute

### ISSUE THREAD

**Issue by bushrang3r** [otakuhqz/Omega#50]
As the title suggests, the options for the double tap gesture don't execute.

I want the phone to sleep when I double tap the home screen, but even if I select this option in the gesture settings, double tapping on the home screen does nothing. It's the same result with the other double tap options too.

* Device: LG G6
* Android version: 10
* Launcher version: 0.7.0
* Rom: HAVOC

**Comment by machiav3lli** [comment]
Did you give it accessability permission?

**Comment by bushrang3r** [comment]
No I didn't. Thanks for the hint. I have given it permission now and it is working correctly.
I wasn't presented with the accessibility permission option when I first selected the double tap setting so I didn't think about needing to do that.
Interesting that the first  time I tried it, nothing happened. 
This time when I tried double tapping the home screen, the 'Downloaded services' settings opened and gave the app permission.

**Comment by machiav3lli** [comment]
@bushrang3r the naming depends on the ROM, so yeah.
@otakuhqz maybe you can add an informing text dialog with a button leading to accessibilty settings. Something like "to be able to use this gesture, you'll need to activate accessibility". "don't want" and "go there" buttons.
