### ISSUE TITLE
Disabling search bar leaves blank space

### ISSUE THREAD

**Issue by limbusdev** [otakuhqz/Omega#51]
## Description

After disabling the search bar in the drawer, that space is still there and simply empty.

## Expected Behavior

That space is removed.

## Actual Behavior

There is empty space where the search bar has been.

## Steps to Reproduce

1. Settings
2. Drawer
3. Disable search bar

## Device and OS

* Device: Samsung Galaxy S8
* Android version: 9
* Launcher version: 0.7.0
* Rom: Stock

<img src="https://user-images.githubusercontent.com/6540152/106733369-199b8880-6612-11eb-9c1d-fcec8e970e8f.png" width="256" />

**Comment by otakuhqz** [comment]
Already fixed in commit 0e29be7. The app update with be posted in the next 4-5 days.
