### ISSUE TITLE
Setting the accent color has no effect on drawer

### ISSUE THREAD

**Issue by limbusdev** [otakuhqz/Omega#53]
## Description

Settings the accent color in the theme settings shows no effect on the drawer.

## Expected Behavior

Go to *"Settings" > "Theme" > "Accent Color" > Choose "Red"*

Active Category name and search glass in app drawer are colored red.

## Actual Behavior

Active Category name and search glass in app drawer are colored greenish.

## Steps to Reproduce

Go to *"Settings" > "Theme" > "Accent Color" > Choose "Red"*

## Device and OS

* Device: Samsung Galaxy S8
* Android version: 9
* Launcher version: 0.7.0
* Rom: Stock

**Comment by otakuhqz** [comment]
The accent color only changes the search icon (when using App Search Provider or S Finder search provider) and the scrollbar.
Please confirm if that changes when you change the color

**Comment by limbusdev** [comment]
Well. Not really. Accent is "purple". Scrollbar and tab underlines are changed. Rest stays dark cyan.
![Uploading Screenshot_20210208-115734_Omega Launcher.jpg…]()

**Comment by limbusdev** [comment]
![Screenshot_20210208-115734_Omega Launcher](https://user-images.githubusercontent.com/6540152/107211253-927d5480-6a05-11eb-8984-1f68ecb2b371.jpg)

**Comment by otakuhqz** [comment]
The tab names will have their own color customization. That is why it doesn't change with the accent color.

**Comment by otakuhqz** [comment]
Fixed on v0. 8
