### ISSUE TITLE
Failed to install .apk from Aurora Droid, GitHub page and ADB command.

### ISSUE THREAD

**Issue by TheThunderspy** [otakuhqz/Omega#56]
1. Download the Universal apk file from Aurora Droid, GitHub page and IzzyOnDroid
2. Fails to install the apk file: 
![Screenshot_20210208-120651 1](https://user-images.githubusercontent.com/78750328/107255481-43004e00-6a30-11eb-96da-771ace4fa2cd.png)

3. Run Windows Terminal, execute command from Admin: Command Prompt: adb install com.saggitt.omega_118.apk
4. Fails the Performing Streammed Install with the output error: 
![image](https://user-images.githubusercontent.com/78750328/107254596-5c54ca80-6a2f-11eb-9e91-8f5f6d6e5988.png)

* Device: Bitel B9505
* Android version: Nougat
* Rom: Stock

I'm not a programmer and I don't speak English, so please don't get mad at me if the solution was obvious or if I'm mislead.

**Comment by TheThunderspy** [comment]
Do I need minimun Android 8 or is a problem with my Kernel Version...?

Kernel Version: 3.18.35+

**Comment by otakuhqz** [comment]
Do you speak Spanish?
a lot of features require Android 8. I set API 25 as the minimum requirement but it not tested on that version yet.

**Comment by TheThunderspy** [comment]
Español, Perú
Thank you I didn't know that.
I can't update my device it's EOL, so my options are modding.
I have a question, if it's based in Lawnchair, why is not compatible...?

**Comment by otakuhqz** [comment]
Porque no es un fork directo de Lawnchair. Yo tomo el codigo de Google como base, y luego voy agregando algunas características de Lawnchair y otras que voy desarrollando.
Para hacerlo compatible hay demasiado codigo que modificar y pruebas que realizar. Por el momento soy el unico desarrollador y solo puedo dedicar unas pocas horas al proyecto.

**Comment by TheThunderspy** [comment]
Gracias, voy a cerrar este nudo (nudo suena más cool que problema), Conclusión: La versiòn minima soportada es la API 25 de Android 7.1 no Android 7.0

Thanks, I'm gonna close this issue, Conclussion: The minimum supported version is API 25 (Android 7.1) not Android 7.0
