### ISSUE TITLE
[Feature Request] Allow more customization of radial menu

### ISSUE THREAD

**Issue by LongJohn-Silver** [otakuhqz/Omega#57]
## Description
The [radial menu](https://en.wikipedia.org/wiki/Pie_menu), (as seen in this [screenshot](https://github.com/otakuhqz/omega/blob/master/snapshots/omega2.jpg)) is pretty awesome, but I feel like it could be even better if users would be allowed to set what can be opened there, and if this could be done while you are inside other applications.

## Expected Behavior
A configuration that allows users to choose what can be opened while using the radial menu, and the ability to open it even while inside other applications.

## Actual Behavior
There's no configuration that allows users to choose what can be opened while using the radial menu, and there's no ability to open it even while inside other applications.

## Steps to Reproduce

N/A

## Device and OS
N/A

## Logcat
N/A

**Comment by otakuhqz** [comment]
add on v0.8
