### ISSUE TITLE
[Feature Request] Dock 2nd row

### ISSUE THREAD

**Issue by Diazz72** [otakuhqz/Omega#59]
As title say i would like to request option to add 2nd ( maybe even 3rd if possible 😊 ) row to the dock.

Thanks.

**Comment by Vatroki** [comment]
I second this, would be great to have this option.

**Comment by otakuhqz** [comment]
Added in commit [8779c47](https://github.com/otakuhqz/Omega/commit/8779c47b81486b75f9d2d920b118940ba796e3a3)
