### ISSUE TITLE
Feature Request Please add the ability to remove the app drawer

### ISSUE THREAD

**Issue by odmfl** [otakuhqz/Omega#62]
It would be very nice if you add this feature.  Most stock launchers have this option, for example: asus launcher, samsung launcher, oneplus launcher, oppo launcher ... and many others allow you to choose whether or not to have the app drawer.

This lawnchair fork is without an app drawer.  However, it hasn't received an update in 1 year

https://github.com/renzhn/Lawndesk

There are many people who will appreciate this feature.  I'm sure.

Please consider this request

**Comment by otakuhqz** [comment]
You can have that behavior by changing the swipe-up gesture to "do nothing" and manually adding the shortcuts to the home screen.
the option to completely remove the drawer might be included in the future but today it is not what we want to accomplish with the launcher.

**Comment by zhubinsheng** [comment]
> 如果您添加此功能，那就太好了。大多数股票启动器都有此选项，例如：华硕启动器、三星启动器、一加启动器、oppo 启动器……以及许多其他启动器允许您选择是否拥有应用程序抽屉。
> 
> 这款草坪椅前叉没有应用程序抽屉。但是，它在 1 年内没有收到更新
> 
> https://github.com/renzhn/Lawndesk
> 
> 有很多人会喜欢这个功能。我确定。
> 
> 请考虑这个请求

hi
 i run failed in android studio , did u work Lawndesk succ ?
