### ISSUE TITLE
Cannot build. Cannot find symbol

### ISSUE THREAD

**Issue by coolmarat** [otakuhqz/Omega#65]
## Description
Omega-omega-11\src\com\android\launcher3\Workspace.java:1627: error: cannot find symbol
            ((FolderIcon) child).clearPressedBackground();

## Expected Behavior
Build succesfully

## Actual Behavior
Error while building

## Steps to Reproduce

1.  Menu - Build APK - Build APK

## Device and OS

Device: OnePlus 6t
Android 10

* Device: OnePlus 6t
* Android version: 10
* Launcher version: Launcher3
* Rom: OxygenOS

**Comment by otakuhqz** [comment]
fixed in commit [6b500ed](6b500ed)
