### ISSUE TITLE
Problems with Quickstep (Android 11)

### ISSUE THREAD

**Issue by Dav357** [otakuhqz/Omega#66]
I tried to install Omega on the Android 11 emulator and I found some issues.

## Description

First of all I had to apply some changes (attached here, it's a .diff file, but I had use .txt because Github...):
[GestureState.txt](https://github.com/otakuhqz/Omega/files/6290735/GestureState.txt).
Without these Omega kept crashing on boot when used as recent provider in Quickswitch.
Also, I had to restart the emulator a couple of times after setting Omega as recents provider on Quickswitch, otherwise it did non register correctly and it does not work at all.

## Expected Behavior
I expected to swipe up / press the square key and see my recent apps (complete with icon on top and thumbnail).

## Actual Behavior
The swipe up gesture does not work (at least in the emulator) even when the preferences are set to show recents:
![Preferences](https://user-images.githubusercontent.com/13455609/114284992-111d5f00-9a54-11eb-99cf-893c093075d0.png)
Luckily the square button of the navigation bar works.
Both methods work fine when the Pixel launcher is the recent provider, so I believe something is wrong with Omega,

There is no icon on top and the application register the list of open applications once and show them every subsequent time. (meaning I always see the applications I had the first time I clicked the recents button)
If one of the application has been closed, the thumbnail is white, it is impossible to switch to that application (with the error "App isn't available") and the screenshot button does not work:
![Quickstep2](https://user-images.githubusercontent.com/13455609/114285254-18de0300-9a56-11eb-8b02-bf9d4ba1ec4e.png)![Quickstep](https://user-images.githubusercontent.com/13455609/114285055-68bbca80-9a54-11eb-8b0b-7d2763a6aa4c.png)

## Steps to Reproduce

1. Install Quickswitch
2. Install Omega
3. Set Omega as recents provider:
![Quickswitch](https://user-images.githubusercontent.com/13455609/114285108-de279b00-9a54-11eb-955e-c8c0946b5007.png)
4. Reboot a couple of times
5. Press recents button on navigation bar (square button)

## Device and OS

* Device: Official Android Emulator (AVD)
* Android version: 11
* Launcher version: 0.8.0 (commit e52b39f4752cbaeccbf6426f279d488aa4247844)
* Rom: x86 image

## Logcat
--

Thanks in advance

**Comment by otakuhqz** [comment]
I have tried to reproduce it but I'm not able to root the amulator.
can you please share the steps you follow to root it?

**Comment by Dav357** [comment]
Sure, I followed these instructions: https://github.com/shakalaca/MagiskOnEmulator

**Comment by otakuhqz** [comment]
fixed on build 154
