### ISSUE TITLE
[Multiple feature request] 

### ISSUE THREAD

**Issue by bushrang3r** [otakuhqz/Omega#7]
Hello Saul!

This project looks promising!
I've been using Lawnchair but their 'backup/restore' feature has been broken for over 1 year and they say that fixing it is not a priority, so I thought I might give Omega a try. I'm looking forward to your backup & restore feature 👍

I'd like to make some feature requests.
1. Swipe down anywhere on homescreen opens notifications.
2. Custom number of dock icons.

Do think these things are possible?

**Comment by otakuhqz** [comment]
Both features are coming in the next build.

**Comment by bushrang3r** [comment]
Thanks you sir! 😁

**Comment by otakuhqz** [comment]
Swipe down anywhere on homescreen opens notifications: add in commit [Add Swipe down gesture](https://github.com/otakuhqz/Omega/commit/33e4c96e9688c3edf0ec038df84401dcb7d9e362)
    Custom number of dock icons.  [Add dock size preference](https://github.com/otakuhqz/Omega/commit/1b7148a71ea19be89544b4a7e0fbe137a2663710)
