### ISSUE TITLE
[feature request] custom icon size

### ISSUE THREAD

**Issue by Surendrajat** [otakuhqz/Omega#8]
Thanks for this app. Just deleted the Nova launcher :)

However, I miss the icon resize feature from it.

## Description
After hiding labels the icons look smaller and not so nice. Hopefully increasing icon size will be possible in upcoming releases.

**Comment by otakuhqz** [comment]
I'm working on the preference to change the icon size in the drawer. Once this feature is implemented, I will add the preference for dock and desktop resizing.
the three preferences might be available in the next build in 1-2 weeks.

**Comment by Surendrajat** [comment]
Awesome!

**Comment by otakuhqz** [comment]
added on commit [bd6ae02](https://github.com/otakuhqz/Omega/commit/bd6ae028853a4b01348a19178b615cd2007a93f9).
