### ISSUE TITLE
Fix Needed

### ISSUE THREAD

**Issue by ghost** [otakuhqz/Omega#87]
1. Pls fix AtoZ, ZtoA alphabetical order not work when using custom names for the app.
2. Hidden Apps show in search not work in 0.8.0 pls fix this
3. Work profile switch shown in personal tab also when swipe between main and work profile on app drawer
4. Crash when adjust row height and when change theme 

* Android 11

**Comment by KrisadaFantasy** [comment]
Can confirm. Planning to submit issues as well before I saw this thread. Alphabetic sort uses the original name and not custom name by user. And hidden apps not show up in search regardless of setting. Sorting issue never work for me and hidden app not show up only happen in 0.8.0 and not in 0.7.1

Android 11 on MiA3
