### ISSUE TITLE
Cover mode enabled app groups disappear when moved

### ISSUE THREAD

**Issue by izzel** [otakuhqz/Omega#89]
## Description

App groups using cover mode disappears if moved. Also probably related, cover mode groups occasionally disappear on the dock. The app groups are still there and can be interacted with, but the icon and title aren't visible.

## Expected Behaviour

App group should stay visible.

## Actual Behaviour

App group disappears and stays so until it is long pressed again.

## Steps to Reproduce

1. Create a group and turn cover mode on
2. Move the group to a different position

## Device and OS

* Device: OnePlus 5t
* Android version: 9
* Launcher version: 0.7.1 & 0.8.0
* Rom: Stock

**Comment by otakuhqz** [comment]
Fixex on V0.8.1
