### ISSUE TITLE
Custom icon revert back to original after uninstalling app

### ISSUE THREAD

**Issue by KrisadaFantasy** [otakuhqz/Omega#91]
## Description
Unrelated apps with custom icon revert back to its original icon after uninstalling app.

## Expected Behavior
App with custom icon keep their custom icon.

## Actual Behavior
After uninstalling app, one by one custom icon revert back to original icon. Sometime a few apps retain their custom icon but I cannot figure out how and why. Eventually all revert back to original icon.

## Steps to Reproduce
1. Have apps with custom icon
2. Uninstall app.

https://user-images.githubusercontent.com/85682504/121793427-05534200-cc29-11eb-87db-c0fb96484178.mp4

## Device and OS
* Device: MiA3
* Android version: 11
* Launcher version: 0.8.0
* Rom: Stock ROM

**Comment by chaptergy** [comment]
Not sure if this is related, but an apps icon also changes back to the stock icon when it is updated. So the icon from the current icon pack is not used, but the original one.
