### ISSUE TITLE
Rotate icon at their own place

### ISSUE THREAD

**Issue by J4gQBqqR** [otakuhqz/Omega#99]
## Description
When rotating screen, rotate icons at their own place.

## Expected Behavior
Portrait:
A B
C D
E F

Landscape:
B D F
A C E

## Actual Behavior
Portrait:
A B
C D
E F

Landscape:
A B
C D
E F

## Alternative
Use two separate arrangement for landscape and portrait, **especially row and column grid size**. Let user configure each of them separately.

**Comment by otakuhqz** [comment]
Make that beahavior is not feasible. the user should add the shortcut in portrait and then in landscape. this would be make twice the same action for an option that might have low usage.
